// <auto-generated />
namespace E_Shop_Engine.Services.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class FixAppRoletable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixAppRoletable));
        
        string IMigrationMetadata.Id
        {
            get { return "201809151958011_Fix AppRole table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
